title: "Rhyse Bendell"
description: "Human-AI teaming, cognitive systems, and human factors research"
url: "https://rhyse-bendell.github.io"
baseurl: ""

lang: en
markdown: kramdown
permalink: pretty

remote_theme: alshedivat/al-folio

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-scholar
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-loading-lazy
  - jekyll-optional-front-matter
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-tabs
  - jekyll-toc
  - jemoji
  - jekyll-socials

keywords: human-AI teaming, human factors, cognitive science, human-robot interaction, AI systems

author:
  name: Rhyse Bendell, Ph.D.
  email: rhyben94@gmail.com

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page

scholar:
  source: ./_bibliography/
  bibliography: papers.bib
  style: apa
  locale: en
  sort_by: year,month
  order: descending

navbar_fixed: true
footer_fixed: true
max_width: 1100px

exclude:
  - vendor
  - node_modules
