source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "webrick", "~> 1.8"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "jekyll-scholar"
gem "jekyll-spaceship"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
